<?php
// Script to generate migration contents
$migrationsDir = __DIR__ . '/database/migrations';
$files = scandir($migrationsDir);

foreach ($files as $file) {
    if (strpos($file, 'create_users_table') !== false) {
        $content = file_get_contents($migrationsDir . '/' . $file);
        $content = str_replace(
            "\$table->string('email')->unique();",
            "\$table->string('email')->unique();\n            \$table->string('role')->default('guardian');\n            \$table->string('phone')->nullable();",
            $content
        );
        file_put_contents($migrationsDir . '/' . $file, $content);
    } elseif (strpos($file, 'create_schools_table') !== false) {
        $content = "<?php\n\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\n\nreturn new class extends Migration\n{\n    public function up(): void\n    {\n        Schema::create('schools', function (Blueprint \$table) {\n            \$table->id();\n            \$table->string('name');\n            \$table->string('address')->nullable();\n            \$table->timestamps();\n        });\n    }\n\n    public function down(): void\n    {\n        Schema::dropIfExists('schools');\n    }\n};\n";
        file_put_contents($migrationsDir . '/' . $file, $content);
    } elseif (strpos($file, 'create_academic_years_table') !== false) {
        $content = "<?php\n\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\n\nreturn new class extends Migration\n{\n    public function up(): void\n    {\n        Schema::create('academic_years', function (Blueprint \$table) {\n            \$table->id();\n            \$table->foreignId('school_id')->constrained()->cascadeOnDelete();\n            \$table->string('name');\n            \$table->boolean('is_active')->default(false);\n            \$table->timestamps();\n        });\n    }\n\n    public function down(): void\n    {\n        Schema::dropIfExists('academic_years');\n    }\n};\n";
        file_put_contents($migrationsDir . '/' . $file, $content);
    } elseif (strpos($file, 'create_student_classes_table') !== false) {
        $content = "<?php\n\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\n\nreturn new class extends Migration\n{\n    public function up(): void\n    {\n        Schema::create('student_classes', function (Blueprint \$table) {\n            \$table->id();\n            \$table->foreignId('school_id')->constrained()->cascadeOnDelete();\n            \$table->string('name');\n            \$table->integer('level')->default(1);\n            \$table->timestamps();\n        });\n    }\n\n    public function down(): void\n    {\n        Schema::dropIfExists('student_classes');\n    }\n};\n";
        file_put_contents($migrationsDir . '/' . $file, $content);
    } elseif (strpos($file, 'create_guardians_table') !== false) {
        $content = "<?php\n\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\n\nreturn new class extends Migration\n{\n    public function up(): void\n    {\n        Schema::create('guardians', function (Blueprint \$table) {\n            \$table->id();\n            \$table->foreignId('user_id')->constrained()->cascadeOnDelete();\n            \$table->string('name');\n            \$table->string('phone')->nullable();\n            \$table->string('address')->nullable();\n            \$table->timestamps();\n        });\n    }\n\n    public function down(): void\n    {\n        Schema::dropIfExists('guardians');\n    }\n};\n";
        file_put_contents($migrationsDir . '/' . $file, $content);
    } elseif (strpos($file, 'create_students_table') !== false) {
        $content = "<?php\n\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\n\nreturn new class extends Migration\n{\n    public function up(): void\n    {\n        Schema::create('students', function (Blueprint \$table) {\n            \$table->id();\n            \$table->string('nis')->unique();\n            \$table->string('name');\n            \$table->foreignId('student_class_id')->constrained()->cascadeOnDelete();\n            \$table->foreignId('guardian_id')->constrained()->cascadeOnDelete();\n            \$table->string('phone')->nullable();\n            \$table->enum('status', ['ACTIVE', 'INACTIVE'])->default('ACTIVE');\n            \$table->timestamps();\n        });\n    }\n\n    public function down(): void\n    {\n        Schema::dropIfExists('students');\n    }\n};\n";
        file_put_contents($migrationsDir . '/' . $file, $content);
    } elseif (strpos($file, 'create_bill_types_table') !== false) {
        $content = "<?php\n\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\n\nreturn new class extends Migration\n{\n    public function up(): void\n    {\n        Schema::create('bill_types', function (Blueprint \$table) {\n            \$table->id();\n            \$table->string('name');\n            \$table->timestamps();\n        });\n    }\n\n    public function down(): void\n    {\n        Schema::dropIfExists('bill_types');\n    }\n};\n";
        file_put_contents($migrationsDir . '/' . $file, $content);
    } elseif (strpos($file, 'create_bills_table') !== false) {
        $content = "<?php\n\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\n\nreturn new class extends Migration\n{\n    public function up(): void\n    {\n        Schema::create('bills', function (Blueprint \$table) {\n            \$table->id();\n            \$table->foreignId('student_id')->constrained()->cascadeOnDelete();\n            \$table->foreignId('bill_type_id')->constrained()->cascadeOnDelete();\n            \$table->foreignId('academic_year_id')->constrained()->cascadeOnDelete();\n            \$table->string('period')->nullable();\n            \$table->decimal('amount', 15, 2);\n            \$table->date('due_date');\n            \$table->enum('status', ['UNPAID', 'PARTIAL', 'PAID', 'OVERDUE', 'CANCELLED'])->default('UNPAID');\n            \$table->timestamps();\n        });\n    }\n\n    public function down(): void\n    {\n        Schema::dropIfExists('bills');\n    }\n};\n";
        file_put_contents($migrationsDir . '/' . $file, $content);
    } elseif (strpos($file, 'create_payments_table') !== false) {
        $content = "<?php\n\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\n\nreturn new class extends Migration\n{\n    public function up(): void\n    {\n        Schema::create('payments', function (Blueprint \$table) {\n            \$table->id();\n            \$table->foreignId('bill_id')->constrained()->cascadeOnDelete();\n            \$table->foreignId('student_id')->constrained()->cascadeOnDelete();\n            \$table->string('payment_number')->unique();\n            \$table->decimal('amount', 15, 2);\n            \$table->enum('payment_method', ['CASH', 'TRANSFER', 'QRIS'])->default('CASH');\n            \$table->timestamp('paid_at')->nullable();\n            \$table->enum('status', ['SUCCESS', 'PENDING', 'FAILED'])->default('SUCCESS');\n            \$table->text('notes')->nullable();\n            \$table->timestamps();\n        });\n    }\n\n    public function down(): void\n    {\n        Schema::dropIfExists('payments');\n    }\n};\n";
        file_put_contents($migrationsDir . '/' . $file, $content);
    } elseif (strpos($file, 'create_income_categories_table') !== false) {
        $content = "<?php\n\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\n\nreturn new class extends Migration\n{\n    public function up(): void\n    {\n        Schema::create('income_categories', function (Blueprint \$table) {\n            \$table->id();\n            \$table->string('name');\n            \$table->timestamps();\n        });\n    }\n\n    public function down(): void\n    {\n        Schema::dropIfExists('income_categories');\n    }\n};\n";
        file_put_contents($migrationsDir . '/' . $file, $content);
    } elseif (strpos($file, 'create_incomes_table') !== false) {
        $content = "<?php\n\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\n\nreturn new class extends Migration\n{\n    public function up(): void\n    {\n        Schema::create('incomes', function (Blueprint \$table) {\n            \$table->id();\n            \$table->foreignId('income_category_id')->constrained()->cascadeOnDelete();\n            \$table->string('description');\n            \$table->string('source')->nullable();\n            \$table->decimal('amount', 15, 2);\n            \$table->date('date');\n            \$table->timestamps();\n        });\n    }\n\n    public function down(): void\n    {\n        Schema::dropIfExists('incomes');\n    }\n};\n";
        file_put_contents($migrationsDir . '/' . $file, $content);
    } elseif (strpos($file, 'create_expense_categories_table') !== false) {
        $content = "<?php\n\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\n\nreturn new class extends Migration\n{\n    public function up(): void\n    {\n        Schema::create('expense_categories', function (Blueprint \$table) {\n            \$table->id();\n            \$table->string('name');\n            \$table->timestamps();\n        });\n    }\n\n    public function down(): void\n    {\n        Schema::dropIfExists('expense_categories');\n    }\n};\n";
        file_put_contents($migrationsDir . '/' . $file, $content);
    } elseif (strpos($file, 'create_expenses_table') !== false) {
        $content = "<?php\n\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\n\nreturn new class extends Migration\n{\n    public function up(): void\n    {\n        Schema::create('expenses', function (Blueprint \$table) {\n            \$table->id();\n            \$table->foreignId('expense_category_id')->constrained()->cascadeOnDelete();\n            \$table->string('description');\n            \$table->string('source')->nullable();\n            \$table->decimal('amount', 15, 2);\n            \$table->date('date');\n            \$table->timestamps();\n        });\n    }\n\n    public function down(): void\n    {\n        Schema::dropIfExists('expenses');\n    }\n};\n";
        file_put_contents($migrationsDir . '/' . $file, $content);
    } elseif (strpos($file, 'create_cash_accounts_table') !== false) {
        $content = "<?php\n\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\n\nreturn new class extends Migration\n{\n    public function up(): void\n    {\n        Schema::create('cash_accounts', function (Blueprint \$table) {\n            \$table->id();\n            \$table->string('name');\n            \$table->decimal('balance', 15, 2)->default(0);\n            \$table->timestamps();\n        });\n    }\n\n    public function down(): void\n    {\n        Schema::dropIfExists('cash_accounts');\n    }\n};\n";
        file_put_contents($migrationsDir . '/' . $file, $content);
    }
}
echo "Migrations populated.\n";
